import AuthProvider from "@/components/AuthProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.className} bg-gray-600 pt-2 lg:p-2`}>
          {/* <ClientWrapper>
            <div className="relative max-w-[700px] rounded-xl mx-auto bg-slate-900 text-white  min-h-screen">
              <Navbar />
              {children}
            </div>
          </ClientWrapper> */}
        </body>
      </AuthProvider>
    </html>
  );
}
